name: course_connect
description: A Flutter-based course aggregator platform that helps students find and compare courses
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.18
  provider: ^6.0.5
  http: ^1.1.0
  path_provider: ^2.0.11
  cupertino_icons: ^1.0.5
  vector_math: ^2.1.2
  cached_network_image: ^3.2.3
  shared_preferences: ^2.5.2  # Changed from 2.8.0 to 2.5.2
  url_launcher: ^6.1.14
  lottie: ^3.3.1
  intl: ^0.18.1
  flutter_html: ^3.0.0-beta.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/

  # Removing the fonts section since we don't have the font files
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

